#!/bin/bash

# This macro is used to generate the ROOT dictionaries
# To use the ctest launchers one needs some environment variables which
# are only present when running CMake. To have the same environment at
# the time the dictionary is build this script is used which is build
# at the time cmake runs.

# Setup the needed environment
export LD_LIBRARY_PATH=/home/eicc/software/FairSoft/install/lib::/home/hexh/simulation/ChnsRoot/buildChns/lib:/home/eicc/FairRoot/build_18.4.2/lib:/home/eicc/software/FairSoft/install/lib:/home/eicc/software/FairSoft/install/lib/Geant3-3.7.0/..
export DYLD_LIBRARY_PATH=/home/eicc/software/FairSoft/install/lib::/home/hexh/simulation/ChnsRoot/buildChns/lib:/home/eicc/FairRoot/build_18.4.2/lib:/home/eicc/software/FairSoft/install/lib:/home/eicc/software/FairSoft/install/lib/Geant3-3.7.0/..
export ROOTSYS=/home/eicc/software/FairSoft/install

/home/eicc/software/FairSoft/install/bin/rootcint -f /home/hexh/simulation/ChnsRoot/buildChns/rho/G__RhoDict.cxx -rmf /home/hexh/simulation/ChnsRoot/buildChns/lib/libRho.rootmap -rml Rho.so  -c   -I/home/hexh/simulation/ChnsRoot/field -I/home/hexh/simulation/ChnsRoot/ChnsData -I/home/hexh/simulation/ChnsRoot/ChnsData/PidData -I/home/hexh/simulation/ChnsRoot/rho/RhoBase -I/home/hexh/simulation/ChnsRoot/rho/RhoMath -I/home/hexh/simulation/ChnsRoot/rho/RhoFitter -I/home/hexh/simulation/ChnsRoot/rho/RhoSelector -I/home/hexh/simulation/ChnsRoot/rho/RhoConstraints -I/home/hexh/simulation/ChnsRoot/rho/RhoTools -I/home/hexh/simulation/ChnsRoot/rho/RhoHistogram -I/home/hexh/simulation/ChnsRoot/rho -I/home/hexh/simulation/ChnsRoot/base -I/home/hexh/simulation/ChnsRoot/base/steer -I/home/eicc/software/FairSoft/install/include/root -I/home/eicc/software/FairSoft/install/include -I/home/eicc/FairRoot/build_18.4.2/include RhoConstraints/RhoMassConstraint.h RhoConstraints/RhoPointingConstraint.h RhoConstraints/RhoBeamConstraint.h RhoBase/RhoEventSelectorBase.h RhoTools/RhoCalculationTools.h RhoMath/RhoDoubleErr.h RhoMath/RhoError.h RhoMath/RhoLorentzVectorErr.h RhoMath/RhoVector3Err.h RhoBase/RhoCandidate.h RhoBase/RhoCandList.h RhoBase/RhoCandListIterator.h RhoBase/RhoEventInfo.h RhoBase/RhoFactory.h RhoTools/RhoPdtLoader.h RhoBase/RhoFitterBase.h RhoBase/RhoParticleSelectorBase.h RhoBase/RhoVertexSelectorBase.h RhoSelector/RhoChargedParticleSelector.h RhoSelector/RhoEnergyParticleSelector.h RhoSelector/RhoMassParticleSelector.h RhoSelector/RhoMinusParticleSelector.h RhoSelector/RhoMomentumParticleSelector.h RhoSelector/RhoNeutralParticleSelector.h RhoSelector/RhoPlusParticleSelector.h RhoSelector/RhoSimpleElectronSelector.h RhoSelector/RhoSimpleKaonSelector.h RhoSelector/RhoSimpleMuonSelector.h RhoSelector/RhoSimplePionSelector.h RhoSelector/RhoSimpleProtonSelector.h RhoSelector/RhoSimpleVertexSelector.h RhoSelector/RhoSimpleVertexSelector.h RhoSelector/RhoGoodPhotonSelector.h RhoSelector/RhoGoodTrackSelector.h RhoTools/RhoBooster.h RhoBase/RhoEventShape.h RhoTools/RhoEventShapes.h RhoTools/RhoFindOmittedParticle.h RhoTools/RhoTotalMomentum.h RhoHistogram/RhoColumn.h RhoHistogram/RhoTuple.h RhoBase/RhoConstraint.h Rho_LinkDef.h
