!-------------------------------------------------- -*- fortran -*- ----
! sample jobcard for electron induced reactions, electrons use same program
! parts as neutrinos
! in the following parameters 'neutrino' stands as a synonym for 'electron'
!-----------------------------------------------------------------------
! please visit the GiBUU homepage for further information:
! https://gibuu.hepforge.org
!-----------------------------------------------------------------------

!-----------------------------------------------------------------------
! This jobcard is for fixed Enu, fixed scattering angle of the outgoing
! lepton and output produced for various energy of outgoing lepton
! (dsigma/dcostheta/dEprime xsec nuXsectionMode=1)
!
! see comments to the namelist &neutrino_induced for further
! differential xsec (nuXsectionMode=0-5,7)
!-----------------------------------------------------------------------
! This jobcard would be useful, e.g., for producing single or double differential 
! xsec for inclusive electron scattering
!-----------------------------------------------------------------------
! In this jobcard most of the analysis for final states is switched off, 
! cf. namelist &neutrinoAnalysis;
! The propagation of particles out of the nucleus is also switched off
! (cf. numTimeSteps=0),
! thus we are doing inclusive analysis
! The event output is switched OFF
! for generation of events better use nuXsectionMode=6
! (16 for experimental flux)  and another jobcard as a prototype
!-----------------------------------------------------------------------

************************************************************************
! DON'T FORGET to change "path_to_input" in the namelist &input according 
! to your local GiBUU installation
************************************************************************


!################################################
!init flags
!################################################
!****************
! neutrino init:
!****************

! file: code/init/neutrino/initNeutrino.f90
&neutrino_induced
       process_ID      =  1 ! 1:EM, 2:CC, 3:NC, -1:antiEM, -2:antiCC, -3:antiNC
       flavor_ID       =  1 ! 1:electron, 2:muon, 3:tau

!       nuXsectionMode  =  0 !  0: integratedSigma
      nuXsectionMode  =  1 !  1: dSigmadCosThetadElepton     ! this is the X-section that we want to calculate
!       nuXsectionMode  =  2 !  2: dSigmadQsdElepton
!       nuXsectionMode  =  3 !  3: dSigmadQs
!       nuXsectionMode  =  4 !  4: dSigmadCosTheta
!       nuXsectionMode  =  5 !  5: dSigmadElepton
!       nuXsectionMode  =  6 !  6: dSigmaMC
!       nuXsectionMode  =  7 !  6: dSigmadW
!

!
! The values for nuExp are ! only relevant if nuXsectionmode.ge.10
!
       nuExp           =  0 !  0: noExp

! The following switches specify the elementary processes that are to be taken into account
       includeQE       = T
       includeDELTA    = T
       includeRES      = T
       include1pi      = T         ! 1pi background contribution
       includeDIS      = T
       include2p2hQE   = T
       include2pi      = T         ! 2pi background contribution

       printAbsorptionXS = T               ! This prints out a number of useful inclusive X-sections
/
!#######################################################################################################
! Parameters for groundstate preparation, specifies target mass and switch for comparison with Fermi-gas
! file: code/density/nucleus.f90
!########################################################################################################
&target
      target_Z=18
      target_A=40
      densitySwitch_Static=1    ! 0: density=0.0, 1: Woods-Saxon by Lenske, 2 : NPA 554, 3: Woods-Saxon by Lenske, different neutron and proton radii,
				! 5: density distribution is a sphere with density according to the input value of "fermiMomentum_input".
      fermiMomentum_input=0.225 ! Input value of the fermi momentum for densitySwitch_static=5.
      fermiMotion=.true.
      ReAdjustForConstBinding=.true.
!   ConstBinding=-0.008             ! only valid for ReAdjustForConstBinding=true
/

!#############################################################
! general input, controls among others the statistics of output
!#############################################################


! the number of generated events is proportional (but not equal, because some "events" can be in prohibited phase space)
! to target_A * numEnsembles * num_runs_SameEnergy
! file: code/inputOutput/input.f90
&input
      numEnsembles=200          ! for C12 you can use 4000, for heavier nuclei should be lower; decrease it if there are problems with memory
      eventtype=5               ! 5=neutrino or electron, 200=simple transport of a given particle
      numTimeSteps=0            ! the distance numTimeSteps*delta_T (100*0.2=20 fm in this example) should significantly exceed 
                                ! the radius of the target nucleus, should be 0 for inclusive processes
      delta_T=0.2
      fullensemble=.true.
      localEnsemble=.true.
      num_runs_SameEnergy=1     ! increase these if you want to increase statistics (= number of generated events)
      num_Energies=40      ! for nuXsectionMode=6 or 16 keep this 1, for other nuXsectionMode this is the number of steps in the 
                           !running Q2/Elepton/cosTheta variables, resp.

      freezeRealParticles=.true.
      LRF_equals_CALC_frame=.true. !if .false.: no offshelltransport possible

      path_to_input='~/GiBUU/buuinput'  ! for local run cluster
/

! file: code/density/density.f90
&initDensity
      densitySwitch=2           ! 1=dynamic density according to testparticle density, 2=analytic density prescription 
                                ! 2 uses 'frozen groundstate approximation'.
/

! file: code/density/pauliBlocking.f90
&initPauli
      pauliSwitch     = 2 ! 0: no Pauli blocking, 1: dynamic, 2: analytic      ! has to be '2=analytic' if densitySwitch=2
/


! file: code/init/neutrino/neutrinoXsection.f90
&nl_neutrinoxsection
      singlePiModel=1           ! 0 for HNV, 1 for MAID
      invariantMasscut=5.     ! cut events with invariant mass above
      REScutW=2.0          ! these 4 parameters describe the transition region in Invariant mass W
				! between the resonances and DIS, see "Lalakulich Gallmeister Mosel PRC86(2012)014607" for details
      REScutwidth=0.1
      DIScutW=1.95              ! DIS sets in at this mass (in GeV)
      DIScutwidth=0.1
/




! SPECFIC NEUTRINO FLAGS depending on nuXsectionMode: (choose one)

! relevant for nuXsectionMode=0
! file: code/init/neutrino/neutrinoXsection.f90
!&nl_integratedSigma
!   enu=
!   delta_enu=
!/

! this gives the inclusive X-section as function of energy transfer
! relevant for nuXsectionMode=1

! file: code/init/neutrino/neutrinoXsection.f90
&nl_dSigmadCosThetadElepton
      enu      = 2.222  ! neutrino energy is fixed to 1 GeV
      costheta = 0.963438974 ! fixes cos(outgoing-lepton angle scattering angle with respect to neutrino direction)
      elepton  = 1.2 ! start calculations with energy of the outgoing lepton 
      delta_elepton = 0.025      ! make steps of 0.025;
!     for number of steps set parameter num_Energies in the namelist &input
/

! the following blocks contain input for other cross section calculations, see nuXsectionMode      

! relevant for nuXsectionMode=2 and (except parameter enu) 12
! file: code/init/neutrino/neutrinoXsection.f90
!&nl_dSigmadQsdElepton
!   enu=
!   Qs=
!   elepton=
!   delta_elepton=
!/


! relevant for nuXsectionMode=3 and (except parameter enu) 13
! file: code/init/neutrino/neutrinoXsection.f90
!&nl_dSigmadQs
!   enu=
!   Qs=
!   delta_Qs=
!/

! relevant for nuXsectionMode=4  and (except parameter enu) 14
! file: code/init/neutrino/neutrinoXsection.f90
!&nl_dSigmadCosTheta
!   enu=
!   costheta=
!   delta_costheta=
!/

! relevant for nuXsectionMode=5 and (except parameter enu) 15
! file: code/init/neutrino/neutrinoXsection.f90
!&nl_dSigmadElepton
!   enu=
!   elepton=
!   delta_elepton=
!/

! relevant for nuXsectionMode=6 and (except parameter enu) 16
! file: code/init/neutrino/neutrinoXsection.f90
&nl_SigmaMC
!     MC_xmax=2.0
!      nu=1.0
!/

! relevant for nuXsectionMode=7
&nl_dSigmadW
!       enu = 4.629
!       W = 0.6
!       delta_W = 0.16
/


!********************************************
! Model ingredients
!******************************************

! file: code/init/lowElectron/lepton2p2h.f90
&lepton2p2h
      ME_Version=4            ! This is the Christy model
!      T=0                    ! Isospin of target nucleus, experimental, don't touch
/


! file: code/init/neutrino/matrixelement.f90
&neutrino_matrixelement
      which_resonanceModel=0    !0=QE + matrixelements from MAID, 1=QE matrixelements + old Delta, 2=Rein-Sehgal
/


! Sets axial mass parameter
! file: code/init/lepton/formfactors_QE_nucleon/FF_QE_nucleonScattering.f90
&ff_QE
      parametrization=3         ! 1=BBA03, 2=BBBA05, 3=BBBA07   ! determines the axial mass
      useNonStandardMA=.false.  ! if true, use value of MA_in for axial mass MA, if false, use best fit
!   MA_in=1.0
/



!################################################
!analysis flags
!################################################


!****************
! Neutrino analysis
!****************

! file: code/analysis/neutrinoAnalysis.f90
&neutrinoAnalysis
      inclusiveAnalysis=.true.  !if .true. we don't care whether particles have made it out       
      outputEvents=.false.      ! output list of events and all outgoing particles in each event to the file FinalEvents.dat
/



!################################################
! in-medium width
!################################################

! file: code/width/baryonWidthMedium.f90
&width_Baryon
      mediumSwitch=.false.       ! if .false. vacuum widths will be used for all resonances
                                      ! and other switches are not meaningful/relevant
      mediumSwitch_Delta=.false. ! Use Oset broadening of the Delta (only relevant for mediumSwitch_coll=.false.)
                                 ! This switch allows for a coll. broadening of the Delta width, even if all others are free
      mediumSwitch_coll=.false. ! Use collisional broadening of all resonances 
/


! file: code/spectralFunctions/spectralFunc.f90
&spectralFunction
      nuclwidth=0.001           ! nucleon spectral function with this width, introduced to facilitate QE computation.

/

!################################################
! propagation
!################################################

! these parameters control the propagation of testparticles in the potential
! do not touch defaults

! file: code/propagation/propagation.f90
&propagation
      UseHadronic=.true.              ! Whether to use hadronic potentials in propagation
      RungeKuttaOrder=2               ! 1=first order Runge-Kutta, 2=second order Runge-Kutta
      Mode=2                          ! =0 Cascade, =1 Euler, =2 Predictor-Corrector    
/





!################################################
! potentials
!################################################

! file: code/potential/baryonPotential.f90
&baryonPotential
      EQS_Type=5               ! 1=soft mom-dep, 2=hard mom-dep, 3=soft non-mom-dep, 4=hard non-mom-dep,
                                ! 5=medium mom-dep, 14=Cooper potential
      DeltaPot=1                ! 1=2/3 of nucleon potential, 2=100 MeV*rho/rhoNull
      noPerturbativePotential=.false.
      symmetryPotFlag=0  ! Switch for the assymetry term in the nucleon potential
/


! file: code/potential/coulomb/coulomb.f90
&Coulomb
      CoulombFlag=.true.
/


!################################################
! collision term
!################################################

! file: code/collisions/collisionTerm.f90
&collisionTerm
      oneBodyProcesses=.true.
      twoBodyProcesses=.true.
      threeBodyProcesses=.true.
      DoJustAbsorptive=.false.
/


! file: code/collisions/twoBodyReactions/master_2Body.f90
&master_2Body
      mesonMesonScattering=.false.
/



! file: code/collisions/insertion.f90
&insertion
      minimumEnergy=0.005       ! collisions with an energy below this threshold are not allowed
/


! file: code/collisions/twoBodyReactions/HiEnergy/DoCollTools.f90
&pythia
      PARP(91)=0.44             ! sets one of the PYTHIA parameters, appropriate for lower energies  
/
