
#include "EvtGenModels/EvtPPPsiPiPi.hh"
#include "EvtGenModels/EvtPPPsiPiPi_matr2_f0.hh"

double EvtPPPsiPiPi::Matr2_2(double s, EvtVector4R p, EvtVector4R k1, EvtVector4R k2) {
// generated by notebook '/home/luchinsky/Dropbox/DskD/Work/PANDA/2014/pnd_mar14/pgenerators/X3872/macro/pp/compare.nb'
    EvtComplex ii(0,1);
    EvtVector4R     q = k1 + k2;

    double q2 = q.mass2();
    double t = (p1-p).mass2();
    EvtComplex  den1=1./( (p1+p2).mass2() - (mPsi2S-ii*GammaPsi2S/2)*(mPsi2S-ii*GammaPsi2S/2)),
            den2 = 1./( (p1+p2).mass2() - (mHc-ii*GammaHc/2)*(mHc-ii*GammaHc/2)),
            den3 = 1./( (p1-p).mass2() - mp*mp),
            den4 = 1./( (p1-q).mass2() - mp*mp);
      EvtComplex  cden1=conj(den1),
              cden2=conj(den2),
              cden3=conj(den3),
              cden4=conj(den4);

    double prob = abs(8*cden3*den1*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(s + 2*pow(mp,2)) + 
   8*cden1*den3*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(s + 2*pow(mp,2)) + 
   8*cden4*den1*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(s + 2*pow(mp,2)) + 
   8*cden1*den4*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(s + 2*pow(mp,2)) + 
   16*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(s + 2*pow(mp,2)) + 
   16*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(s + 2*pow(mp,2)) + 
   16*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(s + 2*pow(mp,2)) + 
   16*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(s + 2*pow(mp,2)) + 
   4*cden4*den1*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(2*q2 - 2*s - t + pow(mp,2) - pow(mPsi,2)) + 
   4*cden1*den4*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(2*q2 - 2*s - t + pow(mp,2) - pow(mPsi,2)) + 
   8*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(2*q2 - 2*s - t + pow(mp,2) - pow(mPsi,2)) + 
   8*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(2*q2 - 2*s - t + pow(mp,2) - pow(mPsi,2)) + 
   16*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(2*q2 - 2*s - t + pow(mp,2) - pow(mPsi,2)) + 
   2*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*(s - 4*pow(mp,2))*pow(mPsi,2) + 
   2*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*(s - 4*pow(mp,2))*pow(mPsi,2) + 
   2*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*(-s + 4*pow(mp,2))*pow(mPsi,2) + 
   2*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*(-s + 4*pow(mp,2))*pow(mPsi,2) + 
   2*cden3*den1*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   2*cden1*den3*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   2*cden4*den1*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   2*cden1*den4*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   4*cden3*den2*diag2*diag3*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*s*pow(mHc,-1)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   4*cden2*den3*diag2*diag3*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*s*pow(mHc,-1)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   4*cden4*den2*diag2*diag4*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*s*pow(mHc,-1)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   4*cden2*den4*diag2*diag4*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*s*pow(mHc,-1)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   2*cden2*den1*diag1*diag2*g_Hc_Psi_f*g_pp_Hc*g_pp_Psi2S*g_Psi2S_Psi_f*ii*mPsi2S*s*pow(mHc,-1)*
    (q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 2*cden1*den2*diag1*diag2*g_Hc_Psi_f*g_pp_Hc*g_pp_Psi2S*g_Psi2S_Psi_f*ii*mPsi2S*s*
    pow(mHc,-1)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   8*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   8*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   2*cden3*den2*diag2*diag3*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*pow(mHc,-1)*(-q2 + s + pow(mPsi,2))*
    (q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 2*cden2*den3*diag2*diag3*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*pow(mHc,-1)*
    (-q2 + s + pow(mPsi,2))*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) + 
   2*cden4*den2*diag2*diag4*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*pow(mHc,-1)*(-q2 + s + pow(mPsi,2))*
    (q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 2*cden2*den4*diag2*diag4*g_Hc_Psi_f*g_pp_f*g_pp_Hc*g_pp_Psi*ii*mp*pow(mHc,-1)*
    (-q2 + s + pow(mPsi,2))*(q2 - s - 2*t + 2*pow(mp,2) + pow(mPsi,2)) - 
   4*cden3*den1*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(-q2 + s - t + pow(mp,2) + 2*pow(mPsi,2)) - 
   4*cden1*den3*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*(-q2 + s - t + pow(mp,2) + 2*pow(mPsi,2)) - 
   8*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(-q2 + s - t + pow(mp,2) + 2*pow(mPsi,2)) - 
   8*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(-q2 + s - t + pow(mp,2) + 2*pow(mPsi,2)) - 
   16*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*(-q2 + s - t + pow(mp,2) + 2*pow(mPsi,2)) + 
   4*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*
    (2*pow(mp,2)*pow(mPsi,2) + (-q2 + s + t - pow(mp,2))*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*
    (2*pow(mp,2)*pow(mPsi,2) + (-q2 + s + t - pow(mp,2))*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden3*den1*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden1*den3*diag1*diag3*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden4*den1*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden1*den4*diag1*diag4*g_pp_f*g_pp_Psi*g_pp_Psi2S*g_Psi2S_Psi_f*mp*mPsi2S*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   8*cden4*den3*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   8*cden3*den4*diag3*diag4*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   8*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   8*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*pow(mp,2)*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2))) + 
   4*cden3*den3*pow(diag3,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*
    ((q2 - s - t)*t - pow(mp,4) + (-q2 + t)*pow(mPsi,2) + pow(mp,2)*(-q2 + s + 2*t + 5*pow(mPsi,2))) + 
   4*cden4*den4*pow(diag4,2)*pow(g_pp_f,2)*pow(g_pp_Psi,2)*
    ((q2 - s - t)*t - pow(mp,4) + (-q2 + t)*pow(mPsi,2) + pow(mp,2)*(-q2 + s + 2*t + 5*pow(mPsi,2))) + 
   4*cden1*den1*pow(diag1,2)*pow(g_pp_Psi2S,2)*pow(g_Psi2S_Psi_f,2)*(s + 2*pow(mp,2))*pow(mPsi2S,2) + 
   2*cden1*den1*pow(diag1,2)*pow(g_pp_Psi2S,2)*pow(g_Psi2S_Psi_f,2)*
    (-s + (-q2 + s + t - pow(mp,2))*pow(mPsi,-2)*(-t + pow(mp,2) + pow(mPsi,2)))*pow(mPsi2S,2) + 
   cden2*den2*pow(diag2,2)*pow(g_Hc_Psi_f,2)*pow(g_pp_Hc,2)*pow(mHc,-2)*
    (2*s*pow(mp,4) - 2*pow(mp,2)*(-3*q2*s + 2*s*(s + t) - (2*q2 + 3*s)*pow(mPsi,2) + pow(mPsi,4) + pow(q2,2)) + 
      s*(2*s*t - 2*q2*(s + t) - 2*(s + t)*pow(mPsi,2) + pow(mPsi,4) + pow(q2,2) + pow(s,2) + 2*pow(t,2))));
	 return prob;
}
